backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

display_url: https://great-start-elc.thdi.net # This url will display in the top-right of the CMS

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Custom Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Body, name: body, widget: markdown}
          - {label: Address, name: address, widget: text}
          - {label: Phone, name: phone, widget: string}
          - {label: Email Address, name: email, widget: string}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/blog.md"
        label: "Blog Page"
        name: "blog-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Section 1, name: section1, widget: markdown}
          - {label: Section 2, name: section2, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/parents-family-checklist.md"
        label: "Family Checklist"
        name: "family-checklist"
        fields:
          - {name: template, label: Template, widget: hidden, default: FamilyChecklist}
          - {name: slug, label: Slug, widget: hidden, default: 'parents/family-checklist'}
          - {name: title, label: Title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - label: Checklist
            name: checklist
            required: false
            widget: list
            fields:
              - {name: cell1, label: Item, widget: string, required: false}
          - label: Download Banner
            name: downloadBanner
            required: false
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: File, name: file, widget: file, required: false}
              - {label: Preview Image, name: preview, widget: image, required: false}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/parents-health-medication-information.md"
        label: "Health and Medical Info"
        name: "health-info-page"
        fields:
          - {name: template, label: Template, widget: hidden, default: HealthInfoPage}
          - {name: slug, label: Slug, widget: hidden, default: 'parents/health-information'}
          - {name: title, label: Title, widget: string}
          - {label: Upper Section, name: body, widget: markdown}
          - label: Table
            name: table
            required: false
            widget: object
            fields:
              - label: Headings
                name: headings
                required: false
                widget: list
                fields:
                  - {name: heading, label: Heading, widget: string, required: false}
              - label: items
                name: items
                required: false
                widget: list
                fields:
                  - {name: cell1, label: Cell 1, widget: string, required: false}
                  - {name: cell2, label: Cell 2, widget: string, required: false}
          - {label: Lower Section, name: lowerSection, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {name: template, label: Template, widget: hidden, default: 'HomePage'}
          - {name: slug, label: Slug, widget: hidden, default: ''}
          - {name: title, label: Title, widget: string}
          - {name: subtitle, label: Subtitle, widget: string}
          - {name: featuredImage, label: Featured Image, widget: image}
          - name: homeSection1
            label: Section 1
            widget: object
            required: false
            fields:
              - {name: title, label: Title, widget: string}
              - name: centres
                label: Centres
                widget: list
                fields:
                  - {name: description, label: Description, widget: text, required: false}
                  - {name: logo, label: Logo, widget: image, required: false}
                  - {name: linkTo, label: Link To, widget: string, required: false}
          - name: homeSection2
            label: Section 2
            widget: object
            required: false
            fields:
              - {name: title, label: Title, widget: string}
              - {name: subtitle, label: Subitle, widget: string, required: false}
              - {name: content, label: Content, widget: markdown, required: false}
              - {name: linkTo, label: Link To, widget: string, required: false}
              - {name: image, label: Image, widget: image, required: false}
          - name: homeSection3
            label: Section 3
            widget: object
            required: false
            fields:
              - {name: title, label: Title, widget: string}
              - name: items
                label: Items
                widget: list
                fields:
                  - {name: title, label: Title, widget: string, required: false}
                  - {name: subtitle, label: Subtitle, widget: string, required: false}
                  - {name: icon, label: Icon, widget: image, required: false}
          - name: homeSection4
            label: Section 4
            widget: object
            required: false
            fields:
              - {name: image1, label: Image 1, widget: image}
              - {name: image2, label: Image 2, widget: image}
              - name: items
                label: Items
                widget: list
                fields:
                  - {name: title, label: Title, widget: string, required: false}
                  - {name: description, label: Description, widget: text, required: false}
                  - {name: linkTo, label: Link To, widget: string, required: false}


  - name: defaultPages
    label: Default Page
    editor:
      preview: true
    folder: content/defaultPages
    slug: "{{slug}}"
    delete: false
    create: true
    fields:
      - {label: Template, name: template, widget: hidden, default: DefaultPage}
      - {label: Slug, name: slug, widget: string, default: ''}
      - {label: Title, name: title, widget: string}
      # - {label: Featured Image, name: featuredImage, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
      - label: Download Banner
        name: downloadBanner
        required: false
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: File, name: file, widget: file, required: false}
          - {label: Preview Image, name: preview, widget: image, required: false}
      - label: Accordion
        name: accordion
        required: false
        widget: list
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Content, name: content, widget: markdown, required: false}
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}


  - name: centres
    label: Centre
    editor:
      preview: true
    folder: content/centres
    slug: "{{slug}}"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Template, name: template, widget: hidden, default: Centre}
      # - {label: Slug, name: slug, widget: string, default: ''}
      - {label: Title, name: title, widget: string}
      - {label: Logo, name: logo, widget: image, required: true}
      - {label: Content, name: body, widget: markdown}
      - label: Centre Details
        name: centreDetails
        required: false
        widget: "object"
        fields:
          - {label: Opening Hours, name: openingHours, widget: string, required: false}
          - {label: Location, name: location, widget: string, required: false}
          - {label: Phone, name: phone, widget: string, required: false}
          - {label: Email, name: email, widget: string, required: false}
      - {label: Centre Intro, name: centreIntro, widget: text}
      - label: Classrooms Section
        name: classroomsSection
        required: false
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - label: Items
            name: items
            widget: list
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Icon, name: icon, widget: image, required: false}
              - {label: Subtitle, name: subtitle, widget: string, required: false}
      - label: Testimonials
        name: testimonials
        required: false
        widget: list
        fields:
          - {label: Name, name: name, widget: string, required: false}
          - {label: Testimonial, name: testimonial, widget: text, required: false}
      - label: Director Statement
        name: directorStatement
        required: false
        widget: object
        fields:
          - {label: Title, name: title, widget: text, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Content, name: content, widget: markdown, required: false}
      - label: Gallery Images
        name: gallery
        required: false
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
      - label: Additional Info Boxes
        name: additionalInfoBoxes
        required: false
        widget: list
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Content, name: content, widget: text, required: false}
          - {label: Button Title, name: buttonTitle, widget: string, required: false}
          - {label: Button Link To, name: buttonLinkTo, widget: string, required: false}
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
      - file: "content/settings/footer.yml"
        label: "Footer"
        name: "footer"
        fields:
          - {label: Exceed Banner Text, name: exceedText, widget: string, required: false}
          - {label: Exceed Banner Text (Long), name: exceedTextLong, widget: text, required: false}
          - {label: Exceed Banner Logo, name: exceedLogo, widget: image, required: false}
          - {label: Handbook Image, name: handbookImage, widget: image, required: false}
          - {label: Handbook File, name: handbookFile, widget: file, required: false}
